/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package templates

import (
	"sigs.k8s.io/kubebuilder/v3/pkg/machinery"
)

var _ machinery.Template = &Fake{}

// Readme scaffolds a README.md file
type Fake struct {
	machinery.TemplateMixin
}

// SetTemplateDefaults implements file.Template
func (f *Fake) SetTemplateDefaults() error {
	if f.Path == "" {
		f.Path = "FAKE.md"
	}

	f.TemplateBody = fakeTemplate

	return nil
}

//nolint:lll
const fakeTemplate = `# Fake
This is an unimportant file generated by a test Kubebuilder plugin to show 
Dynamic Bundles
`
